---
dependency:
  name: galaxy
driver:
  name: vagrant
molecule:
  ignore_paths:
    - .git
    - .venv
ansible:
  playbook: tests/playbook.yml
vagrant:
  platforms:
    - name: sierra
      box: jhcook/macos-sierra
      box_version: 10.12.2
    - name: el-capitan
      box: jhcook/osx-elcapitan-10.11
      box_version: 10.11.6
    - name: yosemite
      box: jhcook/osx-yosemite-10.10
      box_version: 10.10.5
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 2048
        cpus: 4
  instances:
    - name: ansible-osx-command-line-tools
      ansible_groups:
        - group1
verifier:
  name: testinfra
  options:
    verbose: true
    connection: ansible
    ansible_inventory: .molecule/ansible_inventory
